[package]
name = "umadb-dcb"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
thiserror = { workspace = true }
uuid = { workspace = true }
futures-core = "0.3"
futures-util = "0.3"
async-trait = { workspace = true }
