name: Build Binaries & Multi-Platform Docker Image

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
env:
  REGISTRY_IMAGE_GHCR: ghcr.io/${{ github.repository_owner }}/umadb
  REGISTRY_IMAGE_DH: umadb/umadb

jobs:
  # -----------------------------
  # Build static MUSL binaries
  # -----------------------------
  build-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
        target: [aarch64-unknown-linux-musl]

    steps:
      # -----------------------------
      # Checkout repository
      # -----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

#  This doesn't actually install the aarch64-unknown-linux-musl on amd64 arch image...
#      # Install musl cross-compiler
#      - name: Install MUSL tools
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y musl musl-tools

      - name: Install xz
        run: sudo apt-get update && sudo apt-get install -y xz-utils

      - name: Download musl-cross
        run: |
          curl -L -o aarch64-musl.tar.xz \
            https://github.com/cross-tools/musl-cross/releases/download/20250929/aarch64-unknown-linux-musl.tar.xz
          mkdir -p $HOME/musl-cross
          tar -xJf aarch64-musl.tar.xz -C $HOME/musl-cross --strip-components=1

      - name: Add musl-cross to PATH
        run: echo "$HOME/musl-cross/bin" >> $GITHUB_PATH

      - name: List musl-cross bin
        run: ls -l $HOME/musl-cross/bin

      - name: Debug PATH
        run: echo $PATH

      - name: Fix permissions
        run: chmod +x $HOME/musl-cross/bin/*


      - name: Test musl compiler
        run: aarch64-unknown-linux-musl-gcc --version

      - name: Configure MUSL cross-compilation
        if: matrix.target == 'aarch64-unknown-linux-musl'
        run: |
          rustup target add aarch64-unknown-linux-musl
          echo "Setting MUSL cross environment"
          echo "CC_aarch64_unknown_linux_musl=aarch64-unknown-linux-musl-gcc" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-unknown-linux-musl-gcc" >> $GITHUB_ENV

      - name: Configure Cargo for aarch64 MUSL
        if: matrix.target == 'aarch64-unknown-linux-musl'
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml <<EOF
          [target.aarch64-unknown-linux-musl]
          linker = "aarch64-unknown-linux-musl-gcc"
          EOF

      - name: Build release binary
        run: |
          cargo build --release --target ${{ matrix.target }} -p umadb-server
          strip target/${{ matrix.target }}/release/umadb

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/umadb

#  # -----------------------------
#  # Build multi-arch Docker image
#  # -----------------------------
#  docker:
#    runs-on: ubuntu-latest
#    needs: build-binaries
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Download binaries
#        uses: actions/download-artifact@v4
#        with:
#          path: ./binaries
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      # -----------------------------
#      # Generate metadata (tags, labels)
#      # -----------------------------
#      - name: Generate Docker metadata
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ${{ env.REGISTRY_IMAGE_GHCR }},${{ env.REGISTRY_IMAGE_DH }}
#          tags: |
#            type=semver,pattern={{version}}
#            type=semver,pattern={{major}}.{{minor}}
#            type=semver,pattern={{major}}
#            type=raw,value=latest,enable=true
#
#      # -----------------------------
#      # Login to registries
#      # -----------------------------
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      # -----------------------------
#      # Build and push multi-platform image
#      # -----------------------------
#      - name: Build and push multi-arch image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: Dockerfile
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          build-args: |
#            UMADB_X86_64=./binaries/x86_64-unknown-linux-musl/umadb
#            UMADB_AARCH64=./binaries/aarch64-unknown-linux-musl/umadb
#          labels: ${{ steps.meta.outputs.labels }}
#          provenance: mode=max       # Attach provenance attestations
#          sbom: true                 # Attach SBOM attestations
#
